
        <?php
        /**
         * @var Codilar\Vendor\Block\ListVendor $block
         **/

        $vendorName=$block->getVendorList();?>
<?php
    foreach ($vendorName as $vendor){
        ?>
        <a href="<?php echo $block->getVendorUrl() ?>id/<?php echo $vendor['id'] ?>">
            <li>
              <b> </b>  <?php echo  __($vendor['name']) ?><b></b>
            </li>
        </a>
    <?php }
?>

